# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\1zadanie\numbers_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.avgLabel = QtWidgets.QLabel(self.centralwidget)
        self.avgLabel.setGeometry(QtCore.QRect(300, 130, 47, 13))
        self.avgLabel.setObjectName("avgLabel")
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setGeometry(QtCore.QRect(300, 110, 47, 13))
        self.minLabel.setObjectName("minLabel")
        self.maxLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxLabel.setGeometry(QtCore.QRect(300, 90, 47, 13))
        self.maxLabel.setObjectName("maxLabel")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.loadButton.setObjectName("loadButton")
        self.saveButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton_2.setGeometry(QtCore.QRect(200, 120, 75, 23))
        self.saveButton_2.setObjectName("saveButton_2")
        self.numbers_text = QtWidgets.QTextEdit(self.centralwidget)
        self.numbers_text.setGeometry(QtCore.QRect(80, 80, 104, 71))
        self.numbers_text.setObjectName("numbers_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.avgLabel.setText(_translate("MainWindow", "avg"))
        self.minLabel.setText(_translate("MainWindow", "min"))
        self.maxLabel.setText(_translate("MainWindow", "max"))
        self.loadButton.setText(_translate("MainWindow", "Download"))
        self.saveButton_2.setText(_translate("MainWindow", "Save"))
