# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\3zadanie\image_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(40, 50, 341, 471))
        self.image_label.setObjectName("image_label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 80, 181, 151))
        self.groupBox.setObjectName("groupBox")
        self.radio_red = QtWidgets.QRadioButton(self.groupBox)
        self.radio_red.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.radio_red.setObjectName("radio_red")
        self.radio_green = QtWidgets.QRadioButton(self.groupBox)
        self.radio_green.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radio_green.setObjectName("radio_green")
        self.radio_blue = QtWidgets.QRadioButton(self.groupBox)
        self.radio_blue.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.radio_blue.setObjectName("radio_blue")
        self.radio_original = QtWidgets.QRadioButton(self.groupBox)
        self.radio_original.setGeometry(QtCore.QRect(20, 120, 82, 17))
        self.radio_original.setObjectName("radio_original")
        self.btn_rotate_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rotate_left.setGeometry(QtCore.QRect(550, 250, 131, 31))
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.btn_rotate_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rotate_right.setGeometry(QtCore.QRect(550, 290, 131, 31))
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(550, 340, 151, 71))
        self.status_label.setObjectName("status_label")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(560, 440, 121, 81))
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.radio_red.setText(_translate("MainWindow", "Red"))
        self.radio_green.setText(_translate("MainWindow", "Green"))
        self.radio_blue.setText(_translate("MainWindow", "Blue"))
        self.radio_original.setText(_translate("MainWindow", "Original"))
        self.btn_rotate_left.setText(_translate("MainWindow", "Left"))
        self.btn_rotate_right.setText(_translate("MainWindow", "Right"))
        self.status_label.setText(_translate("MainWindow", "TextLabel"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
