# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\7zadanie\piano.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_C = QtWidgets.QPushButton(self.centralwidget)
        self.btn_C.setGeometry(QtCore.QRect(50, 220, 31, 91))
        self.btn_C.setObjectName("btn_C")
        self.btn_D = QtWidgets.QPushButton(self.centralwidget)
        self.btn_D.setGeometry(QtCore.QRect(90, 220, 31, 91))
        self.btn_D.setObjectName("btn_D")
        self.btn_E_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_E_2.setGeometry(QtCore.QRect(170, 220, 31, 91))
        self.btn_E_2.setObjectName("btn_E_2")
        self.btn_E = QtWidgets.QPushButton(self.centralwidget)
        self.btn_E.setGeometry(QtCore.QRect(130, 220, 31, 91))
        self.btn_E.setObjectName("btn_E")
        self.btn_B = QtWidgets.QPushButton(self.centralwidget)
        self.btn_B.setGeometry(QtCore.QRect(330, 220, 31, 91))
        self.btn_B.setObjectName("btn_B")
        self.btn_A = QtWidgets.QPushButton(self.centralwidget)
        self.btn_A.setGeometry(QtCore.QRect(290, 220, 31, 91))
        self.btn_A.setObjectName("btn_A")
        self.btn_F = QtWidgets.QPushButton(self.centralwidget)
        self.btn_F.setGeometry(QtCore.QRect(250, 220, 31, 91))
        self.btn_F.setObjectName("btn_F")
        self.btn_G = QtWidgets.QPushButton(self.centralwidget)
        self.btn_G.setGeometry(QtCore.QRect(210, 220, 31, 91))
        self.btn_G.setObjectName("btn_G")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(100, 350, 171, 51))
        self.status_label.setObjectName("status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_C.setText(_translate("MainWindow", "A"))
        self.btn_D.setText(_translate("MainWindow", "B"))
        self.btn_E_2.setText(_translate("MainWindow", "D"))
        self.btn_E.setText(_translate("MainWindow", "C"))
        self.btn_B.setText(_translate("MainWindow", "H"))
        self.btn_A.setText(_translate("MainWindow", "G"))
        self.btn_F.setText(_translate("MainWindow", "F"))
        self.btn_G.setText(_translate("MainWindow", "E"))
        self.status_label.setText(_translate("MainWindow", "TextLabel"))
