# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\8zadanie\l_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(70, 90, 281, 271))
        self.canvas.setObjectName("canvas")
        self.system_name_label = QtWidgets.QLabel(self.centralwidget)
        self.system_name_label.setGeometry(QtCore.QRect(390, 90, 101, 16))
        self.system_name_label.setObjectName("system_name_label")
        self.evolution_slider = QtWidgets.QSlider(self.centralwidget)
        self.evolution_slider.setGeometry(QtCore.QRect(370, 240, 160, 22))
        self.evolution_slider.setOrientation(QtCore.Qt.Horizontal)
        self.evolution_slider.setObjectName("evolution_slider")
        self.step_label = QtWidgets.QLabel(self.centralwidget)
        self.step_label.setGeometry(QtCore.QRect(390, 140, 101, 16))
        self.step_label.setObjectName("step_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.canvas.setText(_translate("MainWindow", "Holst"))
        self.system_name_label.setText(_translate("MainWindow", "Name"))
        self.step_label.setText(_translate("MainWindow", "Name"))
