# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\6zadanie\smilik.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(320, 190, 47, 13))
        self.canvas.setObjectName("canvas")
        self.btn_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(60, 90, 75, 23))
        self.btn_color.setObjectName("btn_color")
        self.scale_slider = QtWidgets.QSlider(self.centralwidget)
        self.scale_slider.setGeometry(QtCore.QRect(20, 180, 160, 22))
        self.scale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.scale_slider.setObjectName("scale_slider")
        self.scale_label = QtWidgets.QLabel(self.centralwidget)
        self.scale_label.setGeometry(QtCore.QRect(70, 340, 47, 13))
        self.scale_label.setObjectName("scale_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 260, 47, 13))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.canvas.setText(_translate("MainWindow", "TextLabel"))
        self.btn_color.setText(_translate("MainWindow", "Color"))
        self.scale_label.setText(_translate("MainWindow", "Percent"))
        self.label.setText(_translate("MainWindow", "Scale"))
