# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\3HomeWork\2zadanie\editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(60, 60, 261, 231))
        self.text_edit.setObjectName("text_edit")
        self.action_new = QtWidgets.QPushButton(self.centralwidget)
        self.action_new.setGeometry(QtCore.QRect(60, 320, 131, 41))
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QPushButton(self.centralwidget)
        self.action_open.setGeometry(QtCore.QRect(60, 370, 131, 41))
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QPushButton(self.centralwidget)
        self.action_save.setGeometry(QtCore.QRect(60, 420, 131, 41))
        self.action_save.setObjectName("action_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.action_new.setText(_translate("MainWindow", "New"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_save.setText(_translate("MainWindow", "Save"))
